"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Tasks", [
      {
        title: "Изучение основ JavaScript",
        description: "Пройти уроки по переменным, типам данных, функциям и циклам на платформе MDN или Codecademy.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Уборка в комнате",
        description: "Разобрать вещи, пропылесосить и протереть пыль.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Изучение асинхронного JS",
        description: "Разобраться с промисами (Promises) и async/await. Написать пример с использованием fetch для получения данных с API.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Изучение песни 'Toxicity'",
        description: "Разобрать текст и аккорды песни 'Toxicity' группы System of a Down.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Работа с DOM",
        description: "Создать простой проект, где можно добавлять и удалять элементы из списка с помощью JavaScript.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Полив цветов",
        description: "Полить все комнатные растения и проверить их на наличие вредителей.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Основы TypeScript",
        description: "Изучить типы данных, интерфейсы и типизацию функций. Написать несколько примеров.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Изучение песни 'Chop Suey!'",
        description: "Разобрать текст и аккорды песни 'Chop Suey!' группы System of a Down.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Практика с массивами и методами",
        description: "Решить 10 задач на методы массивов (map, filter, reduce, forEach) на платформе Codewars или LeetCode.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Поход в магазин",
        description: "Купить продукты: молоко, хлеб, яйца, овощи и фрукты.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Типизация React-компонентов",
        description: "Создать простой React-компонент с использованием TypeScript. Типизировать пропсы и состояние.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Изучение песни 'Aerials'",
        description: "Разобрать текст и аккорды песни 'Aerials' группы System of a Down.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Работа с Generics",
        description: "Разобраться с Generics в TypeScript. Написать универсальную функцию, которая работает с разными типами данных.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Стирка белья",
        description: "Загрузить стиральную машину и развесить постиранное белье.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Настройка TS-конфига",
        description: "Изучить файл `tsconfig.json`. Настроить strict mode, пути для алиасов и другие параметры.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Изучение песни 'B.Y.O.B.'",
        description: "Разобрать текст и аккорды песни 'B.Y.O.B.' группы System of a Down.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Миграция JS-проекта на TS",
        description: "Перенести небольшой JavaScript-проект на TypeScript. Типизировать все функции и объекты.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Приготовление ужина",
        description: "Приготовить пасту с соусом и салат.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Изучение Node.js",
        description: "Создать простой сервер на Node.js, который возвращает 'Hello, World!' при запросе.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Изучение песни 'Lonely Day'",
        description: "Разобрать текст и аккорды песни 'Lonely Day' группы System of a Down.",
        status: "undone",
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Tasks", null, {});
  },
};